services:
  # API Server - główna aplikacja
  ems-api:
    build: .
    container_name: ems-api-server
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - ems-network

  # Device Simulator - symulator urządzeń IoT  
  ems-simulator:
    build: .
    container_name: ems-device-simulator
    depends_on:
      - ems-api
    restart: unless-stopped
    networks:
      - ems-network
    environment:
      - API_URL=http://ems-api:8000
    # Czeka 15 sekund na start API, potem kończy
    entrypoint: ["sh", "-c", "sleep 15 && python device_sim.py || exit 0"]

networks:
  ems-network:
    driver: bridge